/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rental.view;

import rental.dao.*;
import rental.model.Rental;

/**
 *
 * @author HP ProBook
 */
public class FrameDetailRental extends javax.swing.JFrame {

    /**
     * Creates new form FrameDetailRental
     */    
    implementRental implRen = new RentalDao();
    public FrameDetailRental(String kode_rental) {        
        initComponents();
        Rental r = implRen.cariKode(kode_rental);
        lblDetailRental_namaCustomer.setText(r.getNamaCustomer());
        lblDetailRental_noSim.setText(r.getNoSim());
        lblDetailRental_koderental.setText(kode_rental);
        lblDetailRental_alamat.setText(r.getAlamat());
        lblDetailRental_telepon.setText(r.getTelepon());
        lblDetailRental_tanggal.setText(r.getTanggal());
        lblDetailRental_nopol.setText(r.getMobil().getNopol());
        lblDetailRental_tipe.setText(r.getMobil().getTipe());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDetailRental_namaCustomer = new javax.swing.JLabel();
        lblDetailRental_noSim = new javax.swing.JLabel();
        lblDetailRental_koderental = new javax.swing.JLabel();
        lblDetailRental_telepon = new javax.swing.JLabel();
        lblDetailRental_alamat = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDetailRental_nopol = new javax.swing.JLabel();
        lblDetailRental_tipe = new javax.swing.JLabel();
        btnDetailRental_back = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblDetailRental_tanggal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setText("Data Rental");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setText("Nama Customer");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("Kode Rental");

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("No SIM");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Alamat");

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setText("Telepon");

        lblDetailRental_namaCustomer.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblDetailRental_namaCustomer.setText("jLabel7");

        lblDetailRental_noSim.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblDetailRental_noSim.setText("jLabel7");

        lblDetailRental_koderental.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblDetailRental_koderental.setText("jLabel7");

        lblDetailRental_telepon.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblDetailRental_telepon.setText("jLabel7");

        lblDetailRental_alamat.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblDetailRental_alamat.setText("jLabel7");

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setText("Nopol Mobil");

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setText("Tipe Mobil");

        lblDetailRental_nopol.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblDetailRental_nopol.setText("jLabel7");

        lblDetailRental_tipe.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblDetailRental_tipe.setText("jLabel7");

        btnDetailRental_back.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnDetailRental_back.setText("Back");
        btnDetailRental_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailRental_backActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setText("Tanggal Sewa");

        lblDetailRental_tanggal.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblDetailRental_tanggal.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetailRental_back))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDetailRental_tanggal)
                            .addComponent(lblDetailRental_nopol)
                            .addComponent(lblDetailRental_tipe)
                            .addComponent(lblDetailRental_koderental)
                            .addComponent(lblDetailRental_noSim)
                            .addComponent(lblDetailRental_telepon)
                            .addComponent(lblDetailRental_alamat)
                            .addComponent(lblDetailRental_namaCustomer))
                        .addGap(0, 149, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnDetailRental_back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDetailRental_namaCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDetailRental_koderental))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblDetailRental_noSim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblDetailRental_telepon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblDetailRental_alamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblDetailRental_tanggal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblDetailRental_nopol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblDetailRental_tipe))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailRental_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailRental_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnDetailRental_backActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetailRental_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDetailRental_alamat;
    private javax.swing.JLabel lblDetailRental_koderental;
    private javax.swing.JLabel lblDetailRental_namaCustomer;
    private javax.swing.JLabel lblDetailRental_noSim;
    private javax.swing.JLabel lblDetailRental_nopol;
    private javax.swing.JLabel lblDetailRental_tanggal;
    private javax.swing.JLabel lblDetailRental_telepon;
    private javax.swing.JLabel lblDetailRental_tipe;
    // End of variables declaration//GEN-END:variables
}
