/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental.view;

import javax.swing.JOptionPane;
import rental.controller.ControllerMobil;
import rental.model.Mobil;

/**
 *
 * @author HP ProBook
 */
public class FrameDetailMobil extends javax.swing.JFrame {

    /**
     * Creates new form FrameDetailMobil
     *
     * @param id
     */
    String nopol;
    Mobil m;
    ControllerMobil cm = new ControllerMobil(null,this);
    public FrameDetailMobil(String nopol) {
        initComponents();
        m = cm.cariNopol(nopol);
        txtDetailMobil_nopol.setText(nopol);
        txtDetailMobil_tipe.setText(m.getTipe());
        spnDetailMobil_kilometer.setValue(m.getKilometer());
        cm.tampilTableRecordMobil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDetailMobil_tipe = new javax.swing.JTextField();
        txtDetailMobil_nopol = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetailMobil = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnDetailMobil_back = new javax.swing.JButton();
        btnDetailMobil_delete = new javax.swing.JButton();
        btnDetailMobil_update = new javax.swing.JButton();
        spnDetailMobil_kilometer = new javax.swing.JSpinner();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setText("Detail Mobil");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Tipe");

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setText("Kilometer");

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setText("Nopol");

        txtDetailMobil_tipe.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        txtDetailMobil_nopol.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        tblDetailMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetailMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetailMobilMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDetailMobil);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel2.setText("Record Penggunaan Mobil");

        btnDetailMobil_back.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnDetailMobil_back.setText("Back");
        btnDetailMobil_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailMobil_backActionPerformed(evt);
            }
        });

        btnDetailMobil_delete.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnDetailMobil_delete.setText("Delete Mobil");
        btnDetailMobil_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailMobil_deleteActionPerformed(evt);
            }
        });

        btnDetailMobil_update.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnDetailMobil_update.setText("Update Data");
        btnDetailMobil_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailMobil_updateActionPerformed(evt);
            }
        });

        spnDetailMobil_kilometer.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnDetailMobil_update)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDetailMobil_nopol, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                        .addComponent(txtDetailMobil_tipe, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                        .addComponent(spnDetailMobil_kilometer))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDetailMobil_delete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDetailMobil_back)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(119, 119, 119))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDetailMobil_tipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDetailMobil_nopol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spnDetailMobil_kilometer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDetailMobil_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetailMobil_update)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnDetailMobil_back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDetailMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetailMobilMouseClicked

    }//GEN-LAST:event_tblDetailMobilMouseClicked

    private void btnDetailMobil_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailMobil_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnDetailMobil_backActionPerformed

    private void btnDetailMobil_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailMobil_deleteActionPerformed
        if (!txtDetailMobil_nopol.equals("")) {
            int pilih = JOptionPane.showConfirmDialog(null, "Serius mau menghapus data mobilnya??");
            switch(pilih){
                case JOptionPane.YES_OPTION:
                    try {
                        cm.deleteMobil();                        
                        cm.resetDetail();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Nopol gaada!!");
        }
    }//GEN-LAST:event_btnDetailMobil_deleteActionPerformed

    private void btnDetailMobil_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailMobil_updateActionPerformed
        int id = m.getId();
        if (!txtDetailMobil_nopol.equals("")) {
            int pilih = JOptionPane.showConfirmDialog(null, "Serius mau mengganti data mobil ini??");
            switch(pilih){
                case JOptionPane.YES_OPTION:
                    try {
                        cm.updateMobil(id);                                               
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Nopol gaada!!");
        }
    }//GEN-LAST:event_btnDetailMobil_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetailMobil_back;
    private javax.swing.JButton btnDetailMobil_delete;
    private javax.swing.JButton btnDetailMobil_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner spnDetailMobil_kilometer;
    private javax.swing.JTable tblDetailMobil;
    private javax.swing.JTextField txtDetailMobil_nopol;
    private javax.swing.JTextField txtDetailMobil_tipe;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getTxtDetailMobil_nopol() {
        return txtDetailMobil_nopol;
    }

    public javax.swing.JTextField getTxtDetailMobil_tipe() {
        return txtDetailMobil_tipe;
    }

    public void setTxtDetailMobil_nopol(javax.swing.JTextField txtDetailMobil_nopol) {
        this.txtDetailMobil_nopol = txtDetailMobil_nopol;
    }

    public void setTxtDetailMobil_tipe(javax.swing.JTextField txtDetailMobil_tipe) {
        this.txtDetailMobil_tipe = txtDetailMobil_tipe;
    }

    public javax.swing.JSpinner getSpnDetailMobil_kilometer() {
        return spnDetailMobil_kilometer;
    }

    public void setSpnDetailMobil_kilometer(javax.swing.JSpinner spnDetailMobil_kilometer) {
        this.spnDetailMobil_kilometer = spnDetailMobil_kilometer;
    }

    public javax.swing.JTable getTblDetailMobil() {
        return tblDetailMobil;
    }

    public void setTblDetailMobil(javax.swing.JTable tblDetailMobil) {
        this.tblDetailMobil = tblDetailMobil;
    }
}
