/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental.view;

import javax.swing.JOptionPane;
import rental.controller.ControllerMobil;
import rental.controller.ControllerRekap;
import rental.controller.ControllerRental;

/**
 *
 * @author HP ProBook
 */
public class FrameMain extends javax.swing.JFrame {

    ControllerMobil cm;
    ControllerRental cr;
    ControllerRekap crk;
    String klik,klik2;

    public FrameMain() {
        initComponents();
        cm = new ControllerMobil(this,null);
        cr = new ControllerRental(this);
        crk = new ControllerRekap(this);
        cm.tampilTable();
        cr.tampilTable();
        crk.tampilTable();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panePeminjaman = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPeminjaman_namaCustomer = new javax.swing.JTextField();
        txtPeminjaman_alamat = new javax.swing.JTextField();
        txtPeminjaman_noSim = new javax.swing.JTextField();
        txtPeminjaman_mobil = new javax.swing.JTextField();
        txtPeminjaman_telepon = new javax.swing.JTextField();
        btnPeminjaman_save = new javax.swing.JButton();
        panePengembalian = new javax.swing.JPanel();
        txtPengembalian_koderental = new javax.swing.JTextField();
        btnPengembalian_complete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnPeminjaman_cari = new javax.swing.JButton();
        lblPengembalian_namaCustomer = new javax.swing.JLabel();
        lblPengembalian_noSim = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        spnPengembalian_durasi = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        spnPengembalian_kilometer = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        lblPengembalian_Biaya = new javax.swing.JLabel();
        paneTambahMobil = new javax.swing.JPanel();
        txtMobil_tipe = new javax.swing.JTextField();
        btnMobil_tambah = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnMobil_reset = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtMobil_nopol = new javax.swing.JTextField();
        spnMobil_kilometer = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        spnMobil_harga = new javax.swing.JSpinner();
        paneStatusRental = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRental = new javax.swing.JTable();
        btnRental_detail = new javax.swing.JButton();
        paneStatusMobil = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMobil = new javax.swing.JTable();
        btnMobil_details = new javax.swing.JButton();
        paneRekapPendapatan = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPendapatan = new javax.swing.JTable();
        btnPendapatan_detailLain = new javax.swing.JButton();
        lblPendapatan_hariIni = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        panePeminjaman.setBackground(new java.awt.Color(255, 255, 51));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setText("PEMINJAMAN");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("Nama Customer");

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("No Sim/KTP");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Telepon");

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setText("Alamat");

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setText("Mobil");

        txtPeminjaman_namaCustomer.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        txtPeminjaman_alamat.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        txtPeminjaman_noSim.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        txtPeminjaman_mobil.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        txtPeminjaman_telepon.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        btnPeminjaman_save.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnPeminjaman_save.setText("Save");
        btnPeminjaman_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeminjaman_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panePeminjamanLayout = new javax.swing.GroupLayout(panePeminjaman);
        panePeminjaman.setLayout(panePeminjamanLayout);
        panePeminjamanLayout.setHorizontalGroup(
            panePeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePeminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panePeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panePeminjamanLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(86, 86, 86)
                        .addComponent(txtPeminjaman_telepon, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                    .addGroup(panePeminjamanLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(93, 93, 93)
                        .addComponent(txtPeminjaman_alamat, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                    .addGroup(panePeminjamanLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(106, 106, 106)
                        .addComponent(txtPeminjaman_mobil, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                    .addGroup(panePeminjamanLayout.createSequentialGroup()
                        .addGroup(panePeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(panePeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeminjaman_noSim)
                            .addGroup(panePeminjamanLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtPeminjaman_namaCustomer)))
                    .addGroup(panePeminjamanLayout.createSequentialGroup()
                        .addComponent(btnPeminjaman_save)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panePeminjamanLayout.setVerticalGroup(
            panePeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePeminjamanLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panePeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPeminjaman_namaCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panePeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPeminjaman_noSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panePeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtPeminjaman_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panePeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPeminjaman_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panePeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPeminjaman_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnPeminjaman_save)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Peminjaman", panePeminjaman);

        panePengembalian.setBackground(new java.awt.Color(102, 204, 255));

        txtPengembalian_koderental.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        btnPengembalian_complete.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnPengembalian_complete.setText("Complete");
        btnPengembalian_complete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengembalian_completeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setText("Kode Rental");

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel10.setText("Nama Customer");

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel2.setText("PENGEMBALIAN");

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel12.setText("No Sim");

        btnPeminjaman_cari.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnPeminjaman_cari.setText("Cari");

        lblPengembalian_namaCustomer.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblPengembalian_namaCustomer.setText("-");

        lblPengembalian_noSim.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblPengembalian_noSim.setText("-");

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel13.setText("Durasi (hari)");

        spnPengembalian_durasi.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel11.setText("Kilometer (Skrg)");

        spnPengembalian_kilometer.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel14.setText("Total Biaya");

        lblPengembalian_Biaya.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblPengembalian_Biaya.setText("-");

        javax.swing.GroupLayout panePengembalianLayout = new javax.swing.GroupLayout(panePengembalian);
        panePengembalian.setLayout(panePengembalianLayout);
        panePengembalianLayout.setHorizontalGroup(
            panePengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePengembalianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panePengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panePengembalianLayout.createSequentialGroup()
                        .addGroup(panePengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panePengembalianLayout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel2))
                            .addGroup(panePengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPengembalian_namaCustomer)
                                .addGroup(panePengembalianLayout.createSequentialGroup()
                                    .addComponent(btnPengembalian_complete)
                                    .addGap(163, 163, 163))
                                .addComponent(lblPengembalian_noSim)
                                .addComponent(lblPengembalian_Biaya)))
                        .addGap(0, 148, Short.MAX_VALUE))
                    .addGroup(panePengembalianLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panePengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panePengembalianLayout.createSequentialGroup()
                                .addGroup(panePengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addGap(54, 54, 54)
                                .addGroup(panePengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnPengembalian_durasi)
                                    .addComponent(txtPengembalian_koderental)
                                    .addComponent(spnPengembalian_kilometer, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(26, 26, 26)
                                .addComponent(btnPeminjaman_cari))
                            .addGroup(panePengembalianLayout.createSequentialGroup()
                                .addGroup(panePengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel10))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panePengembalianLayout.setVerticalGroup(
            panePengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePengembalianLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addGroup(panePengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPengembalian_koderental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPeminjaman_cari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panePengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(spnPengembalian_durasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panePengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(spnPengembalian_kilometer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(panePengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblPengembalian_namaCustomer))
                .addGap(1, 1, 1)
                .addGroup(panePengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblPengembalian_noSim))
                .addGroup(panePengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panePengembalianLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addGroup(panePengembalianLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPengembalian_Biaya)))
                .addGap(18, 18, 18)
                .addComponent(btnPengembalian_complete)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Pengembalian", panePengembalian);

        paneTambahMobil.setBackground(new java.awt.Color(102, 255, 102));

        txtMobil_tipe.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        btnMobil_tambah.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnMobil_tambah.setText("Tambah");
        btnMobil_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMobil_tambahActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel18.setText("Tipe");

        btnMobil_reset.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnMobil_reset.setText("Reset");

        jLabel19.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel19.setText("Nopol");

        jLabel20.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel20.setText("TAMBAH MOBIL");

        jLabel22.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel22.setText("Kilometer");

        txtMobil_nopol.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        spnMobil_kilometer.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel23.setText("Harga");

        spnMobil_harga.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        javax.swing.GroupLayout paneTambahMobilLayout = new javax.swing.GroupLayout(paneTambahMobil);
        paneTambahMobil.setLayout(paneTambahMobilLayout);
        paneTambahMobilLayout.setHorizontalGroup(
            paneTambahMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTambahMobilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneTambahMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneTambahMobilLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(paneTambahMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneTambahMobilLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                                .addComponent(txtMobil_tipe, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneTambahMobilLayout.createSequentialGroup()
                                .addGroup(paneTambahMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(paneTambahMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMobil_nopol, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(spnMobil_kilometer)
                                    .addComponent(spnMobil_harga))))
                        .addGap(93, 93, 93))
                    .addGroup(paneTambahMobilLayout.createSequentialGroup()
                        .addComponent(btnMobil_tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMobil_reset)
                        .addContainerGap(264, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneTambahMobilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(141, 141, 141))
        );
        paneTambahMobilLayout.setVerticalGroup(
            paneTambahMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTambahMobilLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneTambahMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtMobil_tipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(paneTambahMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtMobil_nopol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneTambahMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(spnMobil_kilometer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneTambahMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(spnMobil_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(paneTambahMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMobil_tambah)
                    .addComponent(btnMobil_reset))
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Tambah Mobil", paneTambahMobil);

        paneStatusRental.setBackground(new java.awt.Color(102, 255, 102));

        tblRental.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        tblRental.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRentalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRental);

        btnRental_detail.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnRental_detail.setText("Detail Rental");
        btnRental_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRental_detailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneStatusRentalLayout = new javax.swing.GroupLayout(paneStatusRental);
        paneStatusRental.setLayout(paneStatusRentalLayout);
        paneStatusRentalLayout.setHorizontalGroup(
            paneStatusRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneStatusRentalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(paneStatusRentalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRental_detail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneStatusRentalLayout.setVerticalGroup(
            paneStatusRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneStatusRentalLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRental_detail)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Status Rental", paneStatusRental);

        paneStatusMobil.setBackground(new java.awt.Color(255, 51, 51));

        tblMobil.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        tblMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nopol", "Tipe", "Kilometer", "Status"
            }
        ));
        tblMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMobilMouseClicked(evt);
            }
        });
        tblMobil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblMobilKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblMobil);
        if (tblMobil.getColumnModel().getColumnCount() > 0) {
            tblMobil.getColumnModel().getColumn(0).setHeaderValue("Nopol");
            tblMobil.getColumnModel().getColumn(1).setHeaderValue("Tipe");
            tblMobil.getColumnModel().getColumn(2).setHeaderValue("Kilometer");
            tblMobil.getColumnModel().getColumn(3).setHeaderValue("Status");
        }

        btnMobil_details.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnMobil_details.setText("Details");
        btnMobil_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMobil_detailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneStatusMobilLayout = new javax.swing.GroupLayout(paneStatusMobil);
        paneStatusMobil.setLayout(paneStatusMobilLayout);
        paneStatusMobilLayout.setHorizontalGroup(
            paneStatusMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneStatusMobilLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(paneStatusMobilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMobil_details)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneStatusMobilLayout.setVerticalGroup(
            paneStatusMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneStatusMobilLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMobil_details)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Status Mobil", paneStatusMobil);

        paneRekapPendapatan.setBackground(new java.awt.Color(153, 0, 153));

        tblPendapatan.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        tblPendapatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblPendapatan);

        btnPendapatan_detailLain.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnPendapatan_detailLain.setText("Detail Lain");

        lblPendapatan_hariIni.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblPendapatan_hariIni.setForeground(new java.awt.Color(255, 255, 255));
        lblPendapatan_hariIni.setText("-");

        jLabel21.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Hasil Pendapatan");

        javax.swing.GroupLayout paneRekapPendapatanLayout = new javax.swing.GroupLayout(paneRekapPendapatan);
        paneRekapPendapatan.setLayout(paneRekapPendapatanLayout);
        paneRekapPendapatanLayout.setHorizontalGroup(
            paneRekapPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(paneRekapPendapatanLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(paneRekapPendapatanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneRekapPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneRekapPendapatanLayout.createSequentialGroup()
                        .addComponent(btnPendapatan_detailLain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPendapatan_hariIni, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneRekapPendapatanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel21)))
                .addContainerGap())
        );
        paneRekapPendapatanLayout.setVerticalGroup(
            paneRekapPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRekapPendapatanLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneRekapPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPendapatan_detailLain)
                    .addComponent(lblPendapatan_hariIni))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Rekap Pendapatan", paneRekapPendapatan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMobil_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMobil_tambahActionPerformed
        try {
            cm.insertMobil();            
            cm.reset();
            cm.tampilTable();            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnMobil_tambahActionPerformed

    private void tblMobilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblMobilKeyPressed

    }//GEN-LAST:event_tblMobilKeyPressed

    private void tblMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMobilMouseClicked
        int row = tblMobil.getSelectedRow();
        klik = (tblMobil.getModel().getValueAt(row, 0).toString());
    }//GEN-LAST:event_tblMobilMouseClicked

    private void btnMobil_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMobil_detailsActionPerformed
        FrameDetailMobil dtl = new FrameDetailMobil(klik);
        dtl.setVisible(true);
    }//GEN-LAST:event_btnMobil_detailsActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        cm.tampilTable();
        cr.tampilTable();
        crk.tampilTable();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btnPeminjaman_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeminjaman_saveActionPerformed
        try {
            cr.insertRental();            
            cr.tampilTable();            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPeminjaman_saveActionPerformed

    private void tblRentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRentalMouseClicked
        int row = tblRental.getSelectedRow();
        klik2 = (tblRental.getModel().getValueAt(row, 0).toString());
    }//GEN-LAST:event_tblRentalMouseClicked

    private void btnRental_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRental_detailActionPerformed
        FrameDetailRental fdm = new FrameDetailRental(klik2);
        fdm.setVisible(true);
    }//GEN-LAST:event_btnRental_detailActionPerformed

    private void btnPengembalian_completeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengembalian_completeActionPerformed
        crk.completeOrder();
        crk.tampilTable();
        crk.reset();
    }//GEN-LAST:event_btnPengembalian_completeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMobil_details;
    private javax.swing.JButton btnMobil_reset;
    private javax.swing.JButton btnMobil_tambah;
    private javax.swing.JButton btnPeminjaman_cari;
    private javax.swing.JButton btnPeminjaman_save;
    private javax.swing.JButton btnPendapatan_detailLain;
    private javax.swing.JButton btnPengembalian_complete;
    private javax.swing.JButton btnRental_detail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblPendapatan_hariIni;
    private javax.swing.JLabel lblPengembalian_Biaya;
    private javax.swing.JLabel lblPengembalian_namaCustomer;
    private javax.swing.JLabel lblPengembalian_noSim;
    private javax.swing.JPanel panePeminjaman;
    private javax.swing.JPanel panePengembalian;
    private javax.swing.JPanel paneRekapPendapatan;
    private javax.swing.JPanel paneStatusMobil;
    private javax.swing.JPanel paneStatusRental;
    private javax.swing.JPanel paneTambahMobil;
    private javax.swing.JSpinner spnMobil_harga;
    private javax.swing.JSpinner spnMobil_kilometer;
    private javax.swing.JSpinner spnPengembalian_durasi;
    private javax.swing.JSpinner spnPengembalian_kilometer;
    private javax.swing.JTable tblMobil;
    private javax.swing.JTable tblPendapatan;
    private javax.swing.JTable tblRental;
    private javax.swing.JTextField txtMobil_nopol;
    private javax.swing.JTextField txtMobil_tipe;
    private javax.swing.JTextField txtPeminjaman_alamat;
    private javax.swing.JTextField txtPeminjaman_mobil;
    private javax.swing.JTextField txtPeminjaman_namaCustomer;
    private javax.swing.JTextField txtPeminjaman_noSim;
    private javax.swing.JTextField txtPeminjaman_telepon;
    private javax.swing.JTextField txtPengembalian_koderental;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JSpinner getSpnMobil_kilometer() {
        return spnMobil_kilometer;
    }

    public javax.swing.JTable getTblMobil() {
        return tblMobil;
    }

    public javax.swing.JTable getTblPendapatan() {
        return tblPendapatan;
    }

    public javax.swing.JTable getTblRental() {
        return tblRental;
    }

    public javax.swing.JTextField getTxtMobil_nopol() {
        return txtMobil_nopol;
    }

    public javax.swing.JTextField getTxtMobil_tipe() {
        return txtMobil_tipe;
    }

    public javax.swing.JTextField getTxtPeminjaman_alamat() {
        return txtPeminjaman_alamat;
    }

    public javax.swing.JTextField getTxtPeminjaman_mobil() {
        return txtPeminjaman_mobil;
    }

    public javax.swing.JTextField getTxtPeminjaman_namaCustomer() {
        return txtPeminjaman_namaCustomer;
    }

    public javax.swing.JTextField getTxtPeminjaman_noSim() {
        return txtPeminjaman_noSim;
    }

    public javax.swing.JTextField getTxtPeminjaman_telepon() {
        return txtPeminjaman_telepon;
    }   

    public javax.swing.JLabel getLblPendapatan_hariIni() {
        return lblPendapatan_hariIni;
    }


    public javax.swing.JLabel getLblPengembalian_namaCustomer() {
        return lblPengembalian_namaCustomer;
    }

    public javax.swing.JLabel getLblPengembalian_noSim() {
        return lblPengembalian_noSim;
    }

    public javax.swing.JButton getBtnMobil_details() {
        return btnMobil_details;
    }

    public javax.swing.JButton getBtnMobil_reset() {
        return btnMobil_reset;
    }

    public javax.swing.JButton getBtnMobil_tambah() {
        return btnMobil_tambah;
    }

    public javax.swing.JButton getBtnPeminjaman_cari() {
        return btnPeminjaman_cari;
    }

    public javax.swing.JButton getBtnPeminjaman_save() {
        return btnPeminjaman_save;
    }

    public javax.swing.JButton getBtnPendapatan_detailLain() {
        return btnPendapatan_detailLain;
    }

    public javax.swing.JButton getBtnPengembalian_complete() {
        return btnPengembalian_complete;
    }
    
    public void setSpnMobil_kilometer(javax.swing.JSpinner spnMobil_kilometer) {
        this.spnMobil_kilometer = spnMobil_kilometer;
    }

    public javax.swing.JSpinner getSpnMobil_harga() {
        return spnMobil_harga;
    }

    public void setSpnMobil_harga(javax.swing.JSpinner spnMobil_harga) {
        this.spnMobil_harga = spnMobil_harga;
    }

    public javax.swing.JSpinner getSpnPengembalian_durasi() {
        return spnPengembalian_durasi;
    }

    public javax.swing.JSpinner getSpnPengembalian_kilometer() {
        return spnPengembalian_kilometer;
    }

    public void setSpnPengembalian_durasi(javax.swing.JSpinner spnPengembalian_durasi) {
        this.spnPengembalian_durasi = spnPengembalian_durasi;
    }

    public void setSpnPengembalian_kilometer(javax.swing.JSpinner spnPengembalian_kilometer) {
        this.spnPengembalian_kilometer = spnPengembalian_kilometer;
    }

    public javax.swing.JTextField getTxtPengembalian_koderental() {
        return txtPengembalian_koderental;
    }

    public void setTxtPengembalian_koderental(javax.swing.JTextField txtPengembalian_koderental) {
        this.txtPengembalian_koderental = txtPengembalian_koderental;
    }

}
